#!/usr/bin/env bash

function docker_package_install {
  source /etc/lsb-release

  sudo -E aptitude install -y docker.io
}

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Darwin)
      brew cask install docker
      brew cask install docker-toolbox
      ;;
    Linux)
      docker_package_install
      sudo usermod -a -G docker ubuntu || true
      sudo usermod -a -G staff ubuntu || true
      ;;
  esac
}

bootstrap
