#!/usr/bin/env bash

function docker_package_install {
  sudo apt-key add "$shome/etc/docker.gpg"

  # Install Docker
  curl -sS -L https://get.docker.com/ | bash
}

function bootstrap {
  local shome="${_docker_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Darwin)
      block compile pkg \
        'https://github.com/docker/toolbox/releases/download/v1.11.1/DockerToolbox-1.11.1.pkg'
      ;;
    Linux)
      docker_package_install
      ;;
  esac
}

bootstrap
