#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Darwin)
      if type -P docker >/dev/null; then
        return 0
      fi
      ;;
    Linux)
      if ! type -P docker-credential-pass >/dev/null; then
        return 1
      fi
      ;;
  esac

  if [[ "$($shome/script/version | jq -r '.docker')" != "$DOCKER_VERSION" ]]; then
    return 1
  fi

  return 0
}

source sub "$BASH_SOURCE" "$@"
