#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if ! type -P docker >/dev/null; then
    return 1
  fi

  case "$(uname -s)" in
    Darwin)
      return 0
      ;;
  esac

  if [[ "$($shome/script/version | jq -r '.docker')" != "$DOCKER_VERSION" ]]; then
    return 1
  fi

  return 0
}

source sub "$BASH_SOURCE" "$@"
