#!/usr/bin/env bash

function _docker_profile {
  local shome="${_docker_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$PATH"

  case "$(uname -s)" in
    Darwin)
      DOCKER_VERSION='1.13.0'
      ;;
    Linux)
      DOCKER_VERSION='1.12.3'
      ;;
  esac
}

_docker_profile
