#!/usr/bin/env bash

function profile {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  PATH="$shome/bin:$shome/exec:$PATH"

  case "$(uname -s)" in
    Darwin)
      export DOCKER_HOST="tcp://127.0.0.1:2375"
      ;;
  esac
}

profile
