#!/usr/bin/env bash

function profile {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  PATH="$shome/bin:$PATH"

  : ${DOCKER_HOST:="tcp://127.0.0.1:2375"}
  export DOCKER_HOST
}

profile
