#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local cmd_docker="$(which /usr/local/bin/docker /usr/bin/docker 2>&- || true)"
  if [[ -x "$cmd_docker" ]]; then
    if [[ -x "$(which docker-machine 2>/dev/null || true)" ]]; then
      if [[ -x "$(which docker-compose 2>/dev/null || true)" ]]; then
        return 1
      fi
    fi
  fi

  return 0
}

source sub "$0" "$@"
