#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local cmd_docker="$(which /usr/local/bin/docker /usr/bin/docker 2>&- || true)"
  if [[ -x "$cmd_docker" ]]; then
    return 1
  fi

  return 0
}

source sub "$0" "$@"
