#!/usr/bin/env bash

function update {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  "$shome/script/bootstrap"

  case "$(uname -s)" in
    Linux)
      docker_package_install 
      echo "net.ipv4.ip_forward=1" | sudo tee /etc/sysctl.d/60-ip-forward.conf
      ;;
  esac
}

update
