#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_docker="$(docker --version 2>/dev/null | awk 'NR == 1 {print $3}' | perl -pe 's{,$}{}' || true)"
  local ver_compose="$(docker-compose version 2>/dev/null | awk 'NR == 1 {print $3}' | perl -pe 's{,$}{}' || true)"
  local ver_machine="$(docker-machine version 2>/dev/null | awk 'NR == 1 {print $3}' | perl -pe 's{,$}{}' || true)"
  jq -n \
    --arg docker "$ver_docker" \
    --arg compose "$ver_compose" \
    --arg machine "$ver_machine" \
    '{docker: $docker, compose: $compose, machine: $machine}'
}

version "$@"
