#!/usr/bin/env bash

function version {
  local shome="${_docker_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  local ver_docker="$(docker --version 2>&- | awk 'NR == 1 {print $3}' | perl -pe 's{,$}{}' || true)"
  jq -n \
    --arg docker "$ver_docker" \
    '{docker: $docker}'
}

version "$@"
